### ISSUE TITLE
format `background` property shorthand semantically

### ISSUE THREAD

**Issue by iFwu** [sjova/vscode-sass-format#7] opened 2017-09-16 03:50 UTC
Something like: 

```css
span {
      background: no-repeat left center / 17px auto url('./img/icon-gps.png');
}
```
will be converted to:
```
span {
      background: no-repeat left (center / 17px) auto url('./img/icon-gps.png');
}
```

In such shorthand, `/` in `left center / 17px auto` is meant to separate `background-position` and `background-size` in order to aviod ambiguity.

I hope this plugin can recognize it and do not wrap it in parentheses.

**Comment by sjova** [comment] 2017-11-04 11:51
Hello iFwu, thanks for reporting this issue.

Sass formatter extension is built on top of `sass-convert`, and reported the issue is the default behavior of sass-convert tool. If you try to use sass-convert as a standalone console tool you will get same results.

Generally, it's really tricky to recognize reported the issue in all possible cases. I'll keep this issue open, and will try to solve issues when I get more free time.

Thanks

**Comment by tyaginboston** [comment] 2018-08-07 17:46
If we could resolve this, would be prefect for my SCSS formatting. all other have some issue but this would be perfect without this issue. Only thing keeping me from recommending to the bigger team.

**Comment by sjova** [comment] 2020-07-28 19:40
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.

**Closed as completed by sjova** 2020-07-28 19:40 UTC
Labels: bug, enhancement, Priority: Lowest
